debug null pointer issue on macos
err message:

```bash
One of the EventListeners had an uncaught exception
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.Member.getEffectiveName()" because the return value of "net.dv8tion.jda.api.events.message.MessageReceivedEvent.getMember()" is null
	at wowchat.discord.Discord.onMessageReceived(Discord.scala:296)
```